#!/bin/sh

module load hdf5/parallel fftw/parallel gsl gmp
AREPO_DIR=/home/alankar/exp-clcrush/arepo
cd $AREPO_DIR
make clean BUILD_DIR=$AREPO_DIR/examples/agn-wind/build \
           CONFIG=$AREPO_DIR/examples/agn-wind/Config.sh \
		   EXEC=$AREPO_DIR/examples/agn-wind/Arepo
make -j16  BUILD_DIR=$AREPO_DIR/examples/agn-wind/build \
           CONFIG=$AREPO_DIR/examples/agn-wind/Config.sh \
		   EXEC=$AREPO_DIR/examples/agn-wind/Arepo
