#!/bin/bash

#SBATCH --job-name="arepo-cc85"
#SBATCH --mail-type=NONE         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=alankardutta@iisc.ac.in    # Where to send mail.  Set this to your email address
#SBATCH -p debug
#SBATCH -t 2-20:00:00  #dd-hh:mm:ss
#SBATCH -n 192
#SBATCH --output=%x-%j.log

echo "Working Directory = $(pwd)"

cd $SLURM_SUBMIT_DIR
export PROG="./Arepo param.txt 1"
mkdir -p ./output
module load hdf5/parallel fftw/parallel gsl gmp

srun $PROG
