#!/bin/bash -l

# Standard output and error:
#SBATCH -o ./tjob.%x.out.%j
#SBATCH -e ./tjob.%x.err.%j
#SBATCH --job-name="ccArp"
#
# Number of nodes and MPI tasks per node:
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=40
#
#SBATCH --mail-type=NONE
#SBATCH --mail-user=alankardutta@iisc.ac.in
#
# Partition
#SBATCH --partition=p.test
# Wall clock limit:
#SBATCH --time=00-00:29:58

# Load compiler and MPI modules with explicit version specifications,
# consistently with the versions used to build the executable.

echo "Working Directory = $(pwd)"

cd $SLURM_SUBMIT_DIR
export PROG="./Arepo" 
export ARGS="param.txt" #2 47"
mkdir -p $SLURM_SUBMIT_DIR/output
module purge
module load gcc/10 openmpi/4 hdf5-mpi/1.12.0 gsl/2.4 fftw-mpi/3.3.10

export LD_LIBRARY_PATH="/mpcdf/soft/SLE_15/packages/skylake/openmpi/gcc_10-10.3.0/4.0.7/lib:/mpcdf/soft/SLE_15/packages/skylake/gsl/gcc_10-10.3.0/2.4/lib:/mpcdf/soft/SLE_15/packages/skylake/fftw/gcc_10-10.3.0-openmpi_4-4.0.7/3.3.10/lib:/mpcdf/soft/SLE_15/packages/skylake/hdf5/gcc_10-10.3.0-openmpi_4-4.0.7/1.12.0/lib:$LD_LIBRARY_PATH"

srun $PROG $ARGS
