#!/bin/bash -l

# Standard output and error:
#SBATCH -o ./tjob.%x.out.%j
#SBATCH -e ./tjob.%x.err.%j
#SBATCH --job-name="Windy"
#
# Number of nodes and MPI tasks per node:
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=40
#
#SBATCH --mail-type=none
#SBATCH --mail-user=alankard@mpa-garching.mpg.de
#
# Partition
#SBATCH --partition=p.test
# Wall clock limit:
#SBATCH --time=00-00:29:58

# Load compiler and MPI modules with explicit version specifications,
# consistently with the versions used to build the executable.
module purge
module load gcc/10 gsl/2.4 openmpi/4 hdf5-mpi/1.12.0 fftw-mpi/3.3.10

export LD_LIBRARY_PATH="/mpcdf/soft/SLE_15/packages/skylake/openmpi/gcc_10-10.3.0/4.0.7/lib:/mpcdf/soft/SLE_15/packages/skylake/gsl/gcc_10-10.3.0/2.4/lib:/mpcdf/soft/SLE_15/packages/skylake/fftw/gcc_10-10.3.0-openmpi_4-4.0.7/3.3.10/lib:/mpcdf/soft/SLE_15/packages/skylake/hdf5/gcc_10-10.3.0-openmpi_4-4.0.7/1.12.0/lib:$LD_LIBRARY_PATH"

cd $SLURM_SUBMIT_DIR
echo "Working Directory = $(pwd)"

# export PROG="./Arepo paramRelax1.txt"
export PROG="./Arepo paramCloudRelaxed.txt"
mkdir -p $SLURM_SUBMIT_DIR/output 

srun $PROG
